// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb1JmcAstDqUAee2hXyh9R6zVKtI1ewL0',
    appId: '1:698787980092:web:7ebfc6f7c35bd8912ff439',
    messagingSenderId: '698787980092',
    projectId: 'bogusapp-c0d05',
    authDomain: 'bogusapp-c0d05.firebaseapp.com',
    storageBucket: 'bogusapp-c0d05.firebasestorage.app',
    measurementId: 'G-62V76MC05S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKTpv7WwOtBPhdrU3BzcBqom8de2JroNg',
    appId: '1:698787980092:android:44d5687801812d642ff439',
    messagingSenderId: '698787980092',
    projectId: 'bogusapp-c0d05',
    storageBucket: 'bogusapp-c0d05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgxHqAKYQWTX46PkO5g8AdEB0Z_MppzE',
    appId: '1:698787980092:ios:4978dc9e8c3fe1a22ff439',
    messagingSenderId: '698787980092',
    projectId: 'bogusapp-c0d05',
    storageBucket: 'bogusapp-c0d05.firebasestorage.app',
    iosClientId: '698787980092-gcsov9cgtme8sdt4r5cile55mr3ktbf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bogusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgxHqAKYQWTX46PkO5g8AdEB0Z_MppzE',
    appId: '1:698787980092:ios:4978dc9e8c3fe1a22ff439',
    messagingSenderId: '698787980092',
    projectId: 'bogusapp-c0d05',
    storageBucket: 'bogusapp-c0d05.firebasestorage.app',
    iosClientId: '698787980092-gcsov9cgtme8sdt4r5cile55mr3ktbf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bogusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb1JmcAstDqUAee2hXyh9R6zVKtI1ewL0',
    appId: '1:698787980092:web:d299039b025b035b2ff439',
    messagingSenderId: '698787980092',
    projectId: 'bogusapp-c0d05',
    authDomain: 'bogusapp-c0d05.firebaseapp.com',
    storageBucket: 'bogusapp-c0d05.firebasestorage.app',
    measurementId: 'G-6RMQLMSWCB',
  );
}
